//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace wpfRoute
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<Route>();
            }
        }
    }
    public partial class Route
    {
        [PrimaryKey, AutoIncrement]
        [Unique(Name = "sqlite_autoindex_Route_1", Order = 0)]
        public Int64 Id { get; set; }
        
        public Object Code { get; set; }
        
        public Int64? HouseNum { get; set; }
        
        public Object Street { get; set; }
        
        public Object Unit { get; set; }
        
        public DateTime? Updated { get; set; }
        
        public Int64? Path { get; set; }
        
        public Int64? Seq { get; set; }
        
        public Object Delivery { get; set; }
        
        public Object TVGtext { get; set; }
        
        public Object TempStop { get; set; }
        
        public Object TSDate { get; set; }
        
    }
    
}
